// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not supported yet - missing config.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not supported yet - missing config.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not supported yet - missing config.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not supported yet - missing config.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not supported yet - missing config.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn5eKzvKygZDwEJqhLWWBFjDWHBMM9ns0',
    appId: '1:785312027016:android:e93bb4dfecac905d0c6a3d',
    messagingSenderId: '785312027016',
    projectId: 'root-po-tracker',
    storageBucket: 'root-po-tracker.firebasestorage.app',
  );
}
