// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not supported yet - missing config.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not supported yet - missing config.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not supported yet - missing config.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not supported yet - missing config.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not supported yet - missing config.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvpQ_4f8CWWJqm52XV3C6MliwsPC6Q0s',
    appId: '1:715615200744:android:e90a79d4c8aa0afeb7705d',
    messagingSenderId: '715615200744',
    projectId: 'ecommerce-po-tracking-app',
    storageBucket: 'ecommerce-po-tracking-app.firebasestorage.app',
  );
}
